#----------------------------------------------------------

name: MY_GitHubAction
env:
  APPLICATION_NAME   : "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{ github.sha}}"
  
on: 
  push:
    branches: 
        - main

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello MEssage
      run : echo "Hello World from Testing job"

    - name: Execute fuw commands
      run : |
          echo "Hello Message 1"
          echo "Hello Message 2"
          echo "Application name: ${{ env.APPLICATION_NAME }}"
          
    - name: List current folder
      run : ls -la

    - name: Git clone my repo
      uses: actions/checkout@v1
      
    - name: List current folder
      run : ls -la
      
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
      VAR1 : "This is job level Variable1"
      VAR2 : "This is job level VRIABLE2"
      
    steps:
    - name: Print Hello MEssage
      run : echo "Hello World from Deploy job"

    - name: Print env vars
      run : |
        echo "Var1 = ${{ env.VAR1 }}"
        echo "Var2 = ${{ env.VAR2 }}"
        echo "var3 = $LOCAL_VAR"

      env:
        LOCAL_VAR: "This is Superr local Environment varioble"
    - name: Lets test some packages if there are here 1
      run : aws --version
      

    - name: Lets test some packages if there are here 2
      run : zip --version
    - name: Printing Deployment package
      run : echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
